const ZONES = [
  {
    id: "forest_greenleaf_grove",
    name: "Greenleaf Grove",
    type: "Forest",
    terrain_color: "#4F8F45",
    richness: 5,
    danger: 2,
    unlockRequirement: 0,
    description: "A warm, leafy hunting ground where squirrels chatter in the branches and sunlight pools between fern beds.",
    events: ["story_firestar_ember", "choice_hunting_party", "reward_fresh_kill_bonanza", "crisis_badger_tracks"]
  },
  {
    id: "forest_owlshade_pines",
    name: "Owlshade Pines",
    type: "Forest",
    terrain_color: "#2F5D3A",
    richness: 4,
    danger: 3,
    unlockRequirement: 5,
    description: "Tall pines hold old owl nests, soft needles, and the smell of hidden mice under the roots.",
    events: ["story_owl_over_camp", "choice_lost_apprentice", "crisis_owl_swoop", "reward_hidden_mouse_nest"]
  },
  {
    id: "forest_fernfall_hollow",
    name: "Fernfall Hollow",
    type: "Forest",
    terrain_color: "#6E9E52",
    richness: 4,
    danger: 2,
    unlockRequirement: 10,
    description: "A sheltered dip full of bracken, fern tunnels, and quiet paths perfect for apprentice training.",
    events: ["story_apprentice_vow", "choice_training_focus", "reward_herb_patch", "crisis_flooded_den"]
  },
  {
    id: "forest_bramblekit_copse",
    name: "Bramblekit Copse",
    type: "Forest",
    terrain_color: "#3E6F3F",
    richness: 3,
    danger: 3,
    unlockRequirement: 18,
    description: "A tangled patch of bramble and hazel where prey is plentiful, but paws can snag if cats rush.",
    events: ["choice_hunting_party", "crisis_thorn_tangle", "reward_kitten_discovery", "story_warrior_code_echo"]
  },
  {
    id: "forest_birchwhisker_woods",
    name: "Birchwhisker Woods",
    type: "Forest",
    terrain_color: "#7B9B69",
    richness: 4,
    danger: 4,
    unlockRequirement: 30,
    description: "Pale birches creak in the wind, their fallen bark marking trails that only careful patrols can follow.",
    events: ["story_rustling_birches", "choice_border_scent", "crisis_fox_den", "reward_starcrossed_feather"]
  },
  {
    id: "forest_elderleaf_glade",
    name: "Elderleaf Glade",
    type: "Forest",
    terrain_color: "#527A4A",
    richness: 5,
    danger: 3,
    unlockRequirement: 46,
    description: "An old clearing where elders say StarClan once sent dreams through dew clinging to elder leaves.",
    events: ["story_starclan_dream", "choice_elder_counsel", "reward_ancient_cache", "crisis_greencough_scare"]
  },
  {
    id: "river_minnow_bend",
    name: "Minnow Bend",
    type: "River",
    terrain_color: "#4FA3B8",
    richness: 4,
    danger: 2,
    unlockRequirement: 0,
    description: "A gentle river curve where minnows flash like silver claws beneath smooth stones.",
    events: ["story_river_sparkle", "choice_fishing_lesson", "reward_silver_minnows", "crisis_slippery_bank"]
  },
  {
    id: "river_reedwhisper_bank",
    name: "Reedwhisper Bank",
    type: "River",
    terrain_color: "#5D9FA3",
    richness: 5,
    danger: 3,
    unlockRequirement: 14,
    description: "Reeds whisper beside the water, hiding frogs, water voles, and the occasional rival scent.",
    events: ["choice_border_scent", "choice_fishing_lesson", "crisis_river_surge", "reward_reedbed_vole"]
  },
  {
    id: "river_silverstream_ford",
    name: "Silverstream Ford",
    type: "River",
    terrain_color: "#8FC9D7",
    richness: 3,
    danger: 4,
    unlockRequirement: 32,
    description: "A shining ford where the river runs shallow enough to cross, unless rain has swollen its teeth.",
    events: ["story_moonlit_ford", "choice_save_or_chase", "crisis_flooded_crossing", "reward_moonlit_fish"]
  },
  {
    id: "river_troutpool_marsh",
    name: "Troutpool Marsh",
    type: "River",
    terrain_color: "#4B857B",
    richness: 5,
    danger: 4,
    unlockRequirement: 55,
    description: "A marshy pool thick with reeds, frogs, herbs, and treacherous mud that can swallow a careless paw.",
    events: ["crisis_mud_trap", "choice_medicine_cat_route", "reward_rare_herbs", "story_fog_on_water"]
  },
  {
    id: "moor_windrunner_rise",
    name: "Windrunner Rise",
    type: "Moor",
    terrain_color: "#B99B54",
    richness: 3,
    danger: 2,
    unlockRequirement: 8,
    description: "Open grass ripples like fur in the wind, and rabbits dart between shallow dips in the earth.",
    events: ["story_moor_wind", "choice_chase_rabbits", "reward_rabbit_run", "crisis_hawk_shadow"]
  },
  {
    id: "moor_heatherstep_field",
    name: "Heatherstep Field",
    type: "Moor",
    terrain_color: "#A7798C",
    richness: 4,
    danger: 3,
    unlockRequirement: 20,
    description: "Purple heather hides skylark nests and narrow paths that WindClan cats would admire.",
    events: ["choice_training_focus", "choice_heather_patrol", "reward_heather_nest", "crisis_lost_in_fog"]
  },
  {
    id: "moor_rabbitflight_hollow",
    name: "Rabbitflight Hollow",
    type: "Moor",
    terrain_color: "#C0AA68",
    richness: 5,
    danger: 3,
    unlockRequirement: 38,
    description: "A bowl of springy grass where rabbits gather at dusk, tempting any fast-pawed hunter.",
    events: ["choice_chase_rabbits", "crisis_rabbit_burrow_collapse", "reward_fresh_kill_bonanza", "story_apprentice_vow"]
  },
  {
    id: "moor_skygrass_ridge",
    name: "Skygrass Ridge",
    type: "Moor",
    terrain_color: "#D0B56A",
    richness: 3,
    danger: 5,
    unlockRequirement: 68,
    description: "A high ridge of wind-flattened grass where patrols can see far, but storms arrive without warning.",
    events: ["story_storm_clouds", "choice_warning_beacon", "crisis_lightning_strike", "reward_eagle_feather_sign"]
  },
  {
    id: "shadow_pinebog_thicket",
    name: "Pinebog Thicket",
    type: "Shadow Forest",
    terrain_color: "#263E32",
    richness: 3,
    danger: 4,
    unlockRequirement: 25,
    description: "A dark, damp thicket where pine needles sink into black mud and every shadow feels watchful.",
    events: ["story_shadow_scent", "choice_medicine_cat_route", "crisis_snake_in_bog", "reward_night_mushroom_glow"]
  },
  {
    id: "shadow_carrionmist_hollow",
    name: "Carrionmist Hollow",
    type: "Shadow Forest",
    terrain_color: "#2A3329",
    richness: 2,
    danger: 5,
    unlockRequirement: 50,
    description: "Mist clings to the ground, carrying the sour scent of carrion and the hush of unseen paws.",
    events: ["story_broken_branch_omen", "choice_shadow_warning", "crisis_sickness_spread", "reward_hidden_spring"]
  },
  {
    id: "shadow_nightshade_tangle",
    name: "Nightshade Tangle",
    type: "Shadow Forest",
    terrain_color: "#1F2B24",
    richness: 4,
    danger: 5,
    unlockRequirement: 72,
    description: "A dangerous tangle of dark leaves and twisted roots where rare herbs grow beside poisonous stems.",
    events: ["choice_poison_or_cure", "crisis_poisoned_prey", "reward_rare_herbs", "story_starclan_dream"]
  },
  {
    id: "border_fallen_log",
    name: "Fallen Log Border",
    type: "Rival Border",
    terrain_color: "#8B5B35",
    richness: 2,
    danger: 4,
    unlockRequirement: 12,
    description: "A mossy fallen log marks the old scentline, scratched by claws from more than one Clan.",
    events: ["story_rival_scent", "choice_border_scent", "crisis_rival_patrol", "reward_peace_token"]
  },
  {
    id: "border_scentline_ridge",
    name: "Scentline Ridge",
    type: "Rival Border",
    terrain_color: "#9B734D",
    richness: 2,
    danger: 5,
    unlockRequirement: 40,
    description: "A narrow ridge where the wind tangles scents together and a wrong step can become a challenge.",
    events: ["choice_rival_ambush", "choice_shadow_warning", "crisis_border_skirmish", "story_gathering_whispers"]
  },
  {
    id: "border_twoleg_fence",
    name: "Twoleg Fence",
    type: "Rival Border",
    terrain_color: "#7C6A58",
    richness: 1,
    danger: 5,
    unlockRequirement: 60,
    description: "A rattling fence beside Twolegplace, where kittypet smells mix with rival markers and monsters rumble nearby.",
    events: ["story_twoleg_noise", "choice_save_or_chase", "crisis_monster_near_miss", "reward_kittypet_tip"]
  },
  {
    id: "special_moonpool",
    name: "Moonpool",
    type: "Special",
    terrain_color: "#7E8CCB",
    richness: 2,
    danger: 1,
    unlockRequirement: 44,
    description: "A sacred pool beneath the open sky where medicine cats share dreams with StarClan.",
    events: ["story_moonpool_whisper", "choice_moonpool_vision", "reward_starcrossed_feather", "crisis_false_omen"]
  },
  {
    id: "special_ancient_oak",
    name: "Ancient Oak",
    type: "Special",
    terrain_color: "#6B4F2F",
    richness: 4,
    danger: 2,
    unlockRequirement: 64,
    description: "An enormous oak older than any elder, its roots shaped like sleeping cats and its hollow full of secrets.",
    events: ["story_ancient_oak_memory", "choice_elder_counsel", "reward_ancient_cache", "crisis_falling_limb"]
  },
  {
    id: "mixed_meadowbrook_crossing",
    name: "Meadowbrook Crossing",
    type: "Mixed",
    terrain_color: "#82A86B",
    richness: 4,
    danger: 3,
    unlockRequirement: 28,
    description: "Forest grass meets a clear brook, giving hunters many paths but also many ways to be surprised.",
    events: ["choice_hunting_party", "choice_fishing_lesson", "crisis_slippery_bank", "reward_silver_minnows"]
  },
  {
    id: "mixed_stormfall_ravine",
    name: "Stormfall Ravine",
    type: "Mixed",
    terrain_color: "#666F5B",
    richness: 3,
    danger: 5,
    unlockRequirement: 85,
    description: "A steep ravine where trees, stones, and water collide; brave cats can win glory or disaster here.",
    events: ["story_storm_clouds", "choice_warning_beacon", "crisis_lightning_strike", "reward_eagle_feather_sign"]
  }
];

const EVENTS = [
  { id: "story_firestar_ember", type: "story", weight: { base: 4, leaf_bare: 4, low_territory: 4 }, icon: "🔥", title: "An Ember in the Ash", text: "A tiny ember glows beneath the old fire pit near camp, though no cat remembers leaving flame there. The elders whisper that Firestar once proved a brave heart can change every Clan. Your warriors watch the ember until dawn, wondering if StarClan has lit a path for them.", hasChoice: false, choices: [] },
  { id: "story_moonpool_whisper", type: "story", weight: { base: 3, leaf_bare: 3, low_territory: 3 }, icon: "🌙", title: "Whisper at the Moonpool", text: "The Moonpool lies still as polished stone, reflecting more stars than the sky seems to hold. A voice ripples across the water, too soft to name, warning that courage without wisdom can wound the Clan it means to protect. The medicine cat returns silent, with frost glittering on their whiskers.", hasChoice: false, choices: [] },
  { id: "story_owl_over_camp", type: "story", weight: { base: 3, leaf_bare: 4, low_territory: 3 }, icon: "🦉", title: "The Owl Over Camp", text: "An owl circles camp three times before vanishing beyond the pines. The kits tumble close to the nursery wall, pretending not to be frightened. The oldest elder says owls sometimes carry warnings, but they also carry the promise that hidden things can be seen.", hasChoice: false, choices: [] },
  { id: "story_apprentice_vow", type: "story", weight: { base: 4, leaf_bare: 4, low_territory: 4 }, icon: "🐾", title: "The Apprentice Vow", text: "At sunset, a nervous apprentice presses their paws into the dust below Leader's Rock. They promise to protect the Clan, respect the warrior code, and learn from every mistake. The Clan answers with cheers loud enough to stir birds from the trees.", hasChoice: false, choices: [] },
  { id: "story_warrior_code_echo", type: "story", weight: { base: 3, leaf_bare: 3, low_territory: 5 }, icon: "📜", title: "Echo of the Warrior Code", text: "Two warriors argue beside the fresh-kill pile over whether hungry kits should be fed before a tired patrol. The answer is written in every elder's eyes before anyone speaks. The warrior code is not a cage; it is the path that keeps a Clan from losing itself.", hasChoice: false, choices: [] },
  { id: "story_rustling_birches", type: "story", weight: { base: 3, leaf_bare: 4, low_territory: 3 }, icon: "🍃", title: "Rustling Birches", text: "The birches rattle though the wind has stopped. A pale leaf spins down and lands at the paws of your patrol leader, marked by three dark spots like claw tips. No enemy appears, but every cat walks home with their ears pricked.", hasChoice: false, choices: [] },
  { id: "story_river_sparkle", type: "story", weight: { base: 4, leaf_bare: 3, low_territory: 4 }, icon: "💧", title: "Sparkles on the River", text: "The river flashes in the morning sun, and for one bright heartbeat every ripple looks like a silver fish. Even the youngest apprentices sit quietly, watching the water's lesson in patience. A Clan that waits well can strike well.", hasChoice: false, choices: [] },
  { id: "story_moor_wind", type: "story", weight: { base: 3, leaf_bare: 5, low_territory: 4 }, icon: "🌾", title: "The Moor Wind Speaks", text: "Wind rushes across the moor and flattens every blade of grass in the same direction. The patrol follows the bending grass and finds fresh rabbit tracks stamped into soft earth. The moor feels empty, but it has been speaking all morning.", hasChoice: false, choices: [] },
  { id: "story_rival_scent", type: "story", weight: { base: 4, leaf_bare: 4, low_territory: 8 }, icon: "⚔️", title: "Scent on the Border", text: "A rival scent crosses the marker line by less than a tail-length. It might be a mistake, or it might be a test. Your warriors renew the markers carefully, because strength is sometimes shown by refusing to be lured into foolishness.", hasChoice: false, choices: [] },
  { id: "story_gathering_whispers", type: "story", weight: { base: 3, leaf_bare: 3, low_territory: 7 }, icon: "🌕", title: "Whispers After the Gathering", text: "At the Gathering, rival cats speak politely, but their tails twitch with secrets. One deputy mentions missing prey, another complains of trespassing, and a third says nothing at all. Under the full moon, silence can be sharper than claws.", hasChoice: false, choices: [] },
  { id: "story_moonlit_ford", type: "story", weight: { base: 3, leaf_bare: 3, low_territory: 3 }, icon: "🌌", title: "Moonlit Ford", text: "Moonlight turns the ford white and cold, like a path laid down by StarClan. Pawprints appear on the far bank before any living cat crosses. By dawn they are gone, but the patrol remembers exactly where they led.", hasChoice: false, choices: [] },
  { id: "story_fog_on_water", type: "story", weight: { base: 3, leaf_bare: 5, low_territory: 3 }, icon: "🌫️", title: "Fog on the Water", text: "Fog rises from the marsh until every reed looks like a ghostly tail. The medicine cat pauses, listening to drops fall from leaf to leaf. Somewhere inside the gray silence, a frog croaks three times, and the patrol turns back just before the mud deepens.", hasChoice: false, choices: [] },
  { id: "story_storm_clouds", type: "story", weight: { base: 4, leaf_bare: 5, low_territory: 4 }, icon: "⛈️", title: "Clouds Like Claws", text: "Storm clouds gather above the ridge in jagged rows. The camp grows tense as thunder grumbles beyond the trees, and even the boldest apprentices keep close to the dens. The sky feels like a rival warrior waiting to leap.", hasChoice: false, choices: [] },
  { id: "story_shadow_scent", type: "story", weight: { base: 3, leaf_bare: 4, low_territory: 6 }, icon: "🌲", title: "Pine and Secrets", text: "A strange scent of pine sap and wet fur drifts through camp before dawn. No pawprints mark the entrance, yet one guard swears they saw eyes shining beyond the thorn barrier. Shadowed forests keep their secrets until a brave cat steps inside.", hasChoice: false, choices: [] },
  { id: "story_broken_branch_omen", type: "story", weight: { base: 3, leaf_bare: 4, low_territory: 5 }, icon: "🪵", title: "The Broken Branch", text: "A branch snaps from an ancient pine and lands pointing straight toward camp. The crack echoes like a warning yowl. The elders say a broken branch may mean a broken promise, and everyone wonders whose promise StarClan has seen.", hasChoice: false, choices: [] },
  { id: "story_twoleg_noise", type: "story", weight: { base: 3, leaf_bare: 3, low_territory: 4 }, icon: "🚗", title: "Twoleg Thunder", text: "Twoleg monsters roar beside the fence until the ground trembles under every paw. A kittypet watches from a garden wall with wide, worried eyes. The forest seems far away, but the warrior code still travels with every Clan cat.", hasChoice: false, choices: [] },
  { id: "story_ancient_oak_memory", type: "story", weight: { base: 2, leaf_bare: 3, low_territory: 2 }, icon: "🌳", title: "Memory in the Ancient Oak", text: "Inside the Ancient Oak, claw marks spiral upward where generations of warriors have sharpened their paws. One mark glows faintly silver in moonlight. No cat knows whose claw made it, but every cat feels proud to stand beneath it.", hasChoice: false, choices: [] },
  { id: "choice_hunting_party", type: "choice", weight: { base: 5, leaf_bare: 6, low_territory: 4 }, icon: "🐿️", title: "Hunting Party", text: "Fresh prey scent curls through the ferns, but the patrol is tired from marking borders. The Clan needs food, yet exhausted hunters make mistakes. Your deputy asks how to divide the patrol before the trail goes cold.", hasChoice: true, choices: [{ label: "Send the fastest hunters after squirrels", effect_description: "More fresh-kill is likely, but tired cats risk scratches and reduced patrol strength tomorrow." }, { label: "Hunt slowly as a full patrol", effect_description: "Food gain is safer and steadier, but the best prey may escape before the cats arrive." }, { label: "Return and rest, trusting tomorrow's hunt", effect_description: "The Clan avoids injury, but the fresh-kill pile may run low and morale may dip." }] },
  { id: "choice_lost_apprentice", type: "choice", weight: { base: 4, leaf_bare: 6, low_territory: 5 }, icon: "🧭", title: "Lost Apprentice", text: "An apprentice fails to return from a moss-gathering task near Owlshade Pines. Rain begins to fall, washing out the easiest scent trail. The leader must choose quickly before night closes the forest.", hasChoice: true, choices: [{ label: "Send a large search patrol", effect_description: "The apprentice is safer, but camp is left with fewer defenders if rivals test the border." }, { label: "Send two expert trackers", effect_description: "The camp stays protected, but the search may take longer and worry will spread." }, { label: "Ask StarClan for a sign first", effect_description: "The medicine cat may reveal a clue, but waiting costs precious daylight." }] },
  { id: "choice_training_focus", type: "choice", weight: { base: 4, leaf_bare: 4, low_territory: 4 }, icon: "🥋", title: "Training Focus", text: "The apprentices bounce around the clearing, eager to prove themselves. One mentor wants battle moves, another wants stalking practice, and the medicine cat asks for help learning herbs. The day's lesson will shape the Clan's future.", hasChoice: true, choices: [{ label: "Practice battle moves", effect_description: "Apprentices become braver in skirmishes, but hunting progress slows for a day." }, { label: "Practice silent stalking", effect_description: "Hunting improves and prey loss falls, but apprentices may feel unprepared for rivals." }, { label: "Study herbs with the medicine cat", effect_description: "Healing reserves improve, but warriors must cover extra patrol duties." }] },
  { id: "choice_border_scent", type: "choice", weight: { base: 5, leaf_bare: 5, low_territory: 9 }, icon: "👃", title: "The Blurred Scentline", text: "Rain has blurred the border markers, and rival scent clings to a fallen leaf on your side. A hot-headed warrior wants to cross over and accuse them. A quieter cat suggests strengthening the scentline and watching.", hasChoice: true, choices: [{ label: "Cross and confront them", effect_description: "Rivals may back down, but the move risks a fight and damages Gathering diplomacy." }, { label: "Renew markers and set a watch", effect_description: "Territory defense improves without open conflict, but rivals may think the Clan is cautious." }, { label: "Send a polite warning at moonhigh", effect_description: "Diplomacy improves if accepted, but the messenger could be mocked or followed." }] },
  { id: "choice_fishing_lesson", type: "choice", weight: { base: 4, leaf_bare: 3, low_territory: 3 }, icon: "🐟", title: "RiverClan Lesson", text: "A RiverClan elder once told your Clan that patience matters more than splashing. Today the river is clear, and fish drift close to shore. Your apprentices are eager, but wet paws and cold water can humble any cat.", hasChoice: true, choices: [{ label: "Let apprentices try first", effect_description: "Apprentices gain confidence and skill, but failed attempts may scare the fish away." }, { label: "Have warriors demonstrate", effect_description: "Food gain is more reliable, but apprentices learn less from doing." }, { label: "Trade a fish for RiverClan advice", effect_description: "Relations may improve and skills may grow, but some proud warriors dislike owing thanks." }] },
  { id: "choice_chase_rabbits", type: "choice", weight: { base: 4, leaf_bare: 4, low_territory: 3 }, icon: "🐇", title: "Rabbit Sprint", text: "A rabbit breaks from the heather and bolts toward the open moor. The fastest warrior can chase it, but the ground ahead is uneven. The patrol has only heartbeats to decide.", hasChoice: true, choices: [{ label: "Send the fastest cat", effect_description: "A big prey reward is possible, but a twisted paw could weaken the patrol." }, { label: "Circle the rabbit with teamwork", effect_description: "The hunt is safer and trains coordination, but the rabbit may escape through a gap." }, { label: "Ignore it and keep scouting", effect_description: "The patrol preserves strength and may discover danger, but loses an obvious meal." }] },
  { id: "choice_heather_patrol", type: "choice", weight: { base: 3, leaf_bare: 4, low_territory: 4 }, icon: "🌸", title: "Heather Patrol", text: "The heather is thick enough to hide prey, patrols, or a frightened kit. A faint rustle moves against the wind. Your cats freeze, waiting for the order.", hasChoice: true, choices: [{ label: "Fan out silently", effect_description: "The patrol may discover hidden prey or spies, but separated cats face more danger alone." }, { label: "Call out a warning", effect_description: "Any hidden cat gets a chance to answer peacefully, but prey and enemies may flee." }, { label: "Retreat and report", effect_description: "The Clan gains information without risk, but a chance to act immediately is lost." }] },
  { id: "choice_save_or_chase", type: "choice", weight: { base: 4, leaf_bare: 5, low_territory: 5 }, icon: "💨", title: "Save or Chase", text: "A thief snatches fresh-kill from a patrol just as a young apprentice slips near danger. The prey thief is getting away, but the apprentice's yowl cuts through the air. The warrior code presses hard on every heart.", hasChoice: true, choices: [{ label: "Save the apprentice first", effect_description: "Clan loyalty and safety rise, but food is lost and the thief grows bolder." }, { label: "Chase the thief", effect_description: "The Clan may recover prey and pride, but the apprentice may suffer a worse injury." }, { label: "Split the patrol", effect_description: "Both problems may be handled, but smaller groups have less strength if trouble doubles." }] },
  { id: "choice_medicine_cat_route", type: "choice", weight: { base: 4, leaf_bare: 6, low_territory: 4 }, icon: "🌿", title: "Medicine Cat Route", text: "The medicine cat needs herbs from a dangerous stretch of marsh before moonrise. One route is short and muddy, another is long but safer, and a rival path may be fastest of all. The sick cats in camp cannot wait forever.", hasChoice: true, choices: [{ label: "Take the short marsh path", effect_description: "Herbs arrive quickly, but there is real risk of mud traps and soaked fur." }, { label: "Take the long safe path", effect_description: "The medicine cat stays safer, but sick cats wait longer and symptoms may worsen." }, { label: "Ask a rival medicine cat for passage", effect_description: "This may build sacred trust, but warriors on both sides may resent the request." }] },
  { id: "choice_elder_counsel", type: "choice", weight: { base: 3, leaf_bare: 4, low_territory: 3 }, icon: "🪶", title: "Elder Counsel", text: "The elders remember a time when this problem came before, though their stories do not fully agree. One says to act boldly, one says to wait, and one says to listen to the kits because kits notice what warriors miss.", hasChoice: true, choices: [{ label: "Follow the bold elder's memory", effect_description: "The Clan acts decisively and may gain territory, but old memories can miss new dangers." }, { label: "Follow the cautious elder's warning", effect_description: "The Clan avoids obvious traps, but rivals may seize momentum." }, { label: "Ask the kits what they noticed", effect_description: "A surprising clue may emerge, but some warriors dislike taking kits seriously." }] },
  { id: "choice_warning_beacon", type: "choice", weight: { base: 4, leaf_bare: 5, low_territory: 5 }, icon: "📣", title: "Warning From the Ridge", text: "From Skygrass Ridge, a patrol spots shapes moving where no friendly patrol should be. The wind is too strong for clear scent, and thunder mutters behind the hills. The Clan can warn camp, investigate, or hide and watch.", hasChoice: true, choices: [{ label: "Race back to warn camp", effect_description: "Camp defenses improve quickly, but the unknown cats may vanish before being identified." }, { label: "Creep closer to investigate", effect_description: "The Clan gains better information, but the patrol may be caught in the open." }, { label: "Hide and observe until dusk", effect_description: "This may reveal rival plans, but the storm could trap the patrol far from camp." }] },
  { id: "choice_shadow_warning", type: "choice", weight: { base: 4, leaf_bare: 5, low_territory: 8 }, icon: "🌑", title: "A Warning From Shadowed Trees", text: "A ShadowClan messenger appears at the edge of the trees, claiming a worse danger is coming. Some warriors hiss that it must be a trick. The messenger's eyes, however, are wide with real fear.", hasChoice: true, choices: [{ label: "Hear the warning in camp", effect_description: "The Clan may gain vital knowledge, but inviting a rival inside unsettles nervous cats." }, { label: "Meet at the border only", effect_description: "Safety and dignity are preserved, but the messenger may reveal less." }, { label: "Refuse and double patrols", effect_description: "The Clan shows strength, but may miss a chance to prepare for a shared threat." }] },
  { id: "choice_moonpool_vision", type: "choice", weight: { base: 3, leaf_bare: 4, low_territory: 4 }, icon: "✨", title: "The Split Vision", text: "At the Moonpool, the medicine cat sees two paths: one of firelight and one of falling snow. Both end at the same dark thornbush. The leader must decide which part of the vision to trust first.", hasChoice: true, choices: [{ label: "Follow the firelight vision", effect_description: "The Clan prepares for action and bravery, but may overlook quieter dangers." }, { label: "Follow the snow vision", effect_description: "The Clan stores food and herbs, but may appear hesitant to rivals." }, { label: "Tell the whole Clan the vision", effect_description: "Everyone can prepare, but fear and rumors may spread among younger cats." }] },
  { id: "choice_rival_ambush", type: "choice", weight: { base: 5, leaf_bare: 5, low_territory: 10 }, icon: "🗡️", title: "Ambush at the Scentline", text: "A rival patrol leaps from behind a fallen log, blocking the path home. Their leader demands your patrol admit weakness in front of apprentices. Every cat waits to see whether pride or strategy wins.", hasChoice: true, choices: [{ label: "Stand ground and challenge them", effect_description: "Warrior confidence rises if successful, but injuries and a larger feud are likely." }, { label: "Withdraw with dignity", effect_description: "The patrol avoids bloodshed, but rivals may boast at the next Gathering." }, { label: "Offer a formal border talk", effect_description: "Diplomacy may expose their motive, but aggressive cats may see it as softness." }] },
  { id: "choice_poison_or_cure", type: "choice", weight: { base: 3, leaf_bare: 5, low_territory: 4 }, icon: "🍄", title: "Poison or Cure", text: "The medicine cat finds two plants growing together: one deadly, one useful for bellyache. A nervous apprentice insists they can tell the difference. The Clan needs the cure, but one mistake could poison the fresh-kill pile.", hasChoice: true, choices: [{ label: "Let the apprentice identify them", effect_description: "The apprentice may gain great skill, but a wrong choice could cause sickness." }, { label: "Have the medicine cat harvest alone", effect_description: "Safety improves, but the apprentice loses a valuable learning moment." }, { label: "Leave both plants untouched", effect_description: "The Clan avoids poison entirely, but misses medicine that may be needed soon." }] },
  { id: "crisis_badger_tracks", type: "crisis", weight: { base: 7, leaf_bare: 10, low_territory: 7 }, icon: "🐾", title: "Badger Tracks by Camp", text: "Huge clawed tracks appear in the mud outside the thorn barrier. The guards count four deep prints, then eight more leading toward the nursery, and every heartbeat matters. Warriors must act now to protect the Clan.", hasChoice: true, choices: [{ label: "Reinforce the nursery first", effect_description: "Kits are best protected, but the medicine den and fresh-kill pile may be exposed." }, { label: "Spread guards evenly", effect_description: "All dens receive protection, but no single point is especially strong." }, { label: "Send a strike patrol to drive it off", effect_description: "The badger may be forced away, but the patrol risks serious injuries." }] },
  { id: "crisis_owl_swoop", type: "crisis", weight: { base: 6, leaf_bare: 8, low_territory: 6 }, icon: "🦉", title: "Owl Swoop", text: "An owl drops from the pines like a silent shadow, scattering the apprentice patrol. Three cats dive under roots, two freeze in the open, and one kit has followed too far from camp. The leader must act before claws strike from above.", hasChoice: true, choices: [{ label: "Call everyone under cover", effect_description: "Most cats are protected quickly, but the hidden kit may stay lost longer." }, { label: "Send one warrior for the kit", effect_description: "The kit may be saved fast, but the rescuer risks the owl's talons." }, { label: "Yowl to distract the owl", effect_description: "The owl may veer away, but the bold cat becomes the main target." }] },
  { id: "crisis_flooded_den", type: "crisis", weight: { base: 6, leaf_bare: 9, low_territory: 6 }, icon: "🌧️", title: "Flooded Den", text: "Rainwater pours into the apprentices' den, soaking nests and dragging moss into the clearing. There are seven nests, only four dry moss bundles, and the storm is not stopping. The Clan must decide who gets shelter first.", hasChoice: true, choices: [{ label: "Move apprentices into the warriors' den", effect_description: "Young cats stay warm, but warriors lose rest and may patrol poorly tomorrow." }, { label: "Use the medicine den's dry moss", effect_description: "Everyone sleeps drier, but sick cats may lack clean bedding." }, { label: "Build a temporary fern shelter", effect_description: "Resources are preserved, but the shelter may fail if rain strengthens." }] },
  { id: "crisis_thorn_tangle", type: "crisis", weight: { base: 5, leaf_bare: 7, low_territory: 5 }, icon: "🌵", title: "Thorn Tangle", text: "A warrior chasing prey crashes into a thorn tangle and cannot pull free without tearing their pelt. The patrol must act quickly to prevent panic from becoming blood loss.", hasChoice: true, choices: [{ label: "Cut the warrior free slowly", effect_description: "Injury is minimized, but the patrol is stuck in dangerous territory longer." }, { label: "Pull free quickly", effect_description: "The warrior escapes fast, but wounds may worsen and need more herbs." }, { label: "Send for the medicine cat immediately", effect_description: "Healing will be better, but the trapped cat must wait in pain." }] },
  { id: "crisis_fox_den", type: "crisis", weight: { base: 8, leaf_bare: 11, low_territory: 8 }, icon: "🦊", title: "Fox Den Discovered", text: "A patrol finds a fox den dug beneath birch roots, with fresh bones scattered outside. The den is close enough that a fox could reach camp before sunset. Warriors must judge whether they have enough strength to act now.", hasChoice: true, choices: [{ label: "Collapse the den entrance", effect_description: "The fox may move away, but trapped foxes can turn furious and dangerous." }, { label: "Set scent markers and avoid it", effect_description: "The Clan reduces risk today, but the fox remains a future threat." }, { label: "Request help from a rival Clan", effect_description: "A shared hunt may succeed, but owing rivals creates political pressure." }] },
  { id: "crisis_greencough_scare", type: "crisis", weight: { base: 7, leaf_bare: 13, low_territory: 7 }, icon: "🤒", title: "Greencough Scare", text: "An elder coughs until the den goes silent, and a kit in the nursery sneezes soon after. The medicine cat counts herbs with a grim face: not enough catmint for every possible patient. The Clan must act before sickness spreads.", hasChoice: true, choices: [{ label: "Isolate elders first", effect_description: "The most vulnerable cats are protected, but families may feel frightened and divided." }, { label: "Save catmint for the sickest only", effect_description: "Herbs last longer, but mild cases may worsen overnight." }, { label: "Send a risky herb patrol", effect_description: "More catmint may be found, but cold patrols can become patients too." }] },
  { id: "crisis_slippery_bank", type: "crisis", weight: { base: 5, leaf_bare: 8, low_territory: 5 }, icon: "🪨", title: "Slippery Bank", text: "Mud crumbles beneath a young warrior's paws, sending them sliding toward fast water. Only two cats are close enough to help. The patrol must act before the current takes hold.", hasChoice: true, choices: [{ label: "Form a tail-chain", effect_description: "The rescue is safer for everyone, but takes precious seconds to organize." }, { label: "One cat leaps immediately", effect_description: "The warrior may be saved fast, but the rescuer could fall too." }, { label: "Throw a branch into reach", effect_description: "Risk to rescuers is lower, but the trapped cat must hold on alone." }] },
  { id: "crisis_river_surge", type: "crisis", weight: { base: 6, leaf_bare: 9, low_territory: 6 }, icon: "🌊", title: "River Surge", text: "The river rises suddenly after rain upstream, swallowing stepping stones one by one. Three cats are on the far bank with fish and herbs. The Clan must decide what crosses first.", hasChoice: true, choices: [{ label: "Bring the cats across first", effect_description: "Lives are prioritized, but herbs and prey may be swept away." }, { label: "Secure the herb bundle first", effect_description: "Medicine is saved, but the stranded cats face the water longer." }, { label: "Wait for the surge to drop", effect_description: "Crossing may become safer, but night and cold increase danger." }] },
  { id: "crisis_flooded_crossing", type: "crisis", weight: { base: 7, leaf_bare: 10, low_territory: 7 }, icon: "🚧", title: "Flooded Crossing", text: "The ford vanishes under churning brown water while a border patrol is still outside. Dusk is closing fast. The leader must decide how many warriors to send searching without leaving camp undefended.", hasChoice: true, choices: [{ label: "Send every available warrior", effect_description: "The lost patrol is more likely to return safely, but camp becomes vulnerable." }, { label: "Send a small expert patrol", effect_description: "Camp stays guarded, but searchers cover less ground." }, { label: "Light a scent trail home", effect_description: "Lost cats may follow it back, but rivals may follow it too." }] },
  { id: "crisis_mud_trap", type: "crisis", weight: { base: 6, leaf_bare: 8, low_territory: 6 }, icon: "🕳️", title: "Mud Trap", text: "A medicine cat sinks chest-deep into marsh mud while carrying precious herbs. The patrol has vines and branches. Every pull must be timed carefully.", hasChoice: true, choices: [{ label: "Use vines as a harness", effect_description: "The rescue is careful and likely successful, but takes longer." }, { label: "Push branches under the paws", effect_description: "The medicine cat may climb free, but the herbs could be lost." }, { label: "Send the apprentice for help", effect_description: "More strength arrives later, but the trapped cat waits in danger." }] },
  { id: "crisis_hawk_shadow", type: "crisis", weight: { base: 5, leaf_bare: 8, low_territory: 5 }, icon: "🦅", title: "Hawk Shadow", text: "A hawk's shadow races across the moor, and a small apprentice is caught in the open. The patrol must spot the safest cover before the hawk folds its wings.", hasChoice: true, choices: [{ label: "Dive for the nearest rabbit hole", effect_description: "The apprentice reaches cover quickly, but the hole may be too narrow." }, { label: "Run for the heather clump", effect_description: "Cover is thicker but farther away." }, { label: "Have warriors leap and yowl", effect_description: "The hawk may be scared off, but warriors risk talons." }] },
  { id: "crisis_lost_in_fog", type: "crisis", weight: { base: 6, leaf_bare: 10, low_territory: 6 }, icon: "🌫️", title: "Lost in Fog", text: "Fog rolls over the moor until every cat looks like a ghost. The patrol hears distant calls, but only one comes from the direction of camp. They must find their way before they wander into rival land.", hasChoice: true, choices: [{ label: "Follow the campward call", effect_description: "The patrol may return quickly, but the call could be an echo." }, { label: "Stay still and wait", effect_description: "No one wanders farther, but cold and fear rise." }, { label: "Mark a circle and scout slowly", effect_description: "The patrol gathers clues, but risks crossing scentlines by mistake." }] },
  { id: "crisis_rabbit_burrow_collapse", type: "crisis", weight: { base: 5, leaf_bare: 7, low_territory: 5 }, icon: "🕳️", title: "Burrow Collapse", text: "The ground caves beneath a chasing apprentice, dropping them into an old rabbit burrow. Their voice echoes from below, frightened but awake. The patrol must judge whether the tunnel will hold before sending help inside.", hasChoice: true, choices: [{ label: "Dig from above", effect_description: "The apprentice can be reached directly, but more dirt may collapse." }, { label: "Enter through the burrow mouth", effect_description: "The rescue may be gentler, but the tunnel is cramped and dark." }, { label: "Wait for stronger warriors", effect_description: "The rescue is safer with more paws, but the apprentice stays trapped longer." }] },
  { id: "crisis_lightning_strike", type: "crisis", weight: { base: 8, leaf_bare: 11, low_territory: 8 }, icon: "⚡", title: "Lightning Strike", text: "Lightning splits a tree near Stormfall Ravine, showering sparks into dry grass. Wind pushes the smoke toward camp. The Clan must choose a firebreak before the blaze chooses for them.", hasChoice: true, choices: [{ label: "Clear leaves near camp", effect_description: "Camp is protected first, but hunting grounds may burn." }, { label: "Drive prey and kits toward the river", effect_description: "Lives are moved from danger, but supplies are left behind." }, { label: "Call rivals to fight the fire", effect_description: "More paws may save the forest, but rivals will see weaknesses in the territory." }] },
  { id: "crisis_snake_in_bog", type: "crisis", weight: { base: 6, leaf_bare: 7, low_territory: 6 }, icon: "🐍", title: "Snake in the Bog", text: "A snake coils beside a clump of herbs, its tongue flicking at the medicine cat's paw. Two warriors can distract it, but one wrong leap may turn a warning hiss into a bite.", hasChoice: true, choices: [{ label: "Distract the snake and grab herbs", effect_description: "The Clan may get the medicine quickly, but warriors risk a bite." }, { label: "Wait for the snake to move", effect_description: "The patrol stays safer, but the herbs may not arrive in time." }, { label: "Abandon this patch", effect_description: "No one is bitten, but the medicine cat must find another source." }] },
  { id: "crisis_sickness_spread", type: "crisis", weight: { base: 7, leaf_bare: 13, low_territory: 7 }, icon: "🦠", title: "Sickness Spreads", text: "By dawn, four cats have coughs and two kits refuse breakfast. The medicine den has limited space. The Clan must act before illness outruns them.", hasChoice: true, choices: [{ label: "Turn the elders' den into a sick den", effect_description: "Sick cats are separated, but elders must move and may feel exposed." }, { label: "Keep families together", effect_description: "Fear drops, but sickness may spread faster." }, { label: "Send healthy cats outside camp", effect_description: "Crowding decreases, but patrol coverage becomes harder to manage." }] },
  { id: "crisis_poisoned_prey", type: "crisis", weight: { base: 6, leaf_bare: 9, low_territory: 6 }, icon: "☠️", title: "Poisoned Prey", text: "A vole on the fresh-kill pile smells wrong, sharp and bitter beneath the prey scent. Three cats have eaten nearby. Fast decisions may save lives.", hasChoice: true, choices: [{ label: "Discard the entire pile", effect_description: "The Clan avoids poison, but hunger rises sharply." }, { label: "Discard only suspicious prey", effect_description: "Some food is saved, but hidden poison may remain." }, { label: "Feed no one until the medicine cat checks", effect_description: "Safety improves, but hungry kits and elders must wait." }] },
  { id: "crisis_rival_patrol", type: "crisis", weight: { base: 7, leaf_bare: 8, low_territory: 12 }, icon: "⚔️", title: "Rival Patrol Pushes In", text: "A rival patrol steps over the border with tails high and claws unsheathed. They outnumber your patrol by two, but your cats know the terrain better.", hasChoice: true, choices: [{ label: "Use the terrain to surround them", effect_description: "The smaller patrol may gain advantage, but the plan requires perfect timing." }, { label: "Call for reinforcements", effect_description: "Strength improves, but rivals gain time to press deeper." }, { label: "Offer a formal challenge", effect_description: "Conflict stays controlled, but the rivals may refuse honor." }] },
  { id: "crisis_border_skirmish", type: "crisis", weight: { base: 8, leaf_bare: 9, low_territory: 13 }, icon: "💥", title: "Border Skirmish", text: "Claws flash at the scentline before any leader can stop them. Three apprentices are watching, two warriors are already bleeding. The Clan must decide whether to escalate, retreat, or force a truce.", hasChoice: true, choices: [{ label: "Pull back immediately", effect_description: "Injuries are limited, but rivals may claim the Clan was driven off." }, { label: "Fight until they retreat", effect_description: "Territory pride may rise, but wounds and grudges deepen." }, { label: "Call on the warrior code", effect_description: "A truce may hold if both sides respect it, but angry cats may ignore words." }] },
  { id: "crisis_monster_near_miss", type: "crisis", weight: { base: 6, leaf_bare: 7, low_territory: 6 }, icon: "🚗", title: "Monster Near Miss", text: "A Twoleg monster screams along the hard path just as a patrol squeezes under the fence. Dust blinds them, and one cat is missing from the count.", hasChoice: true, choices: [{ label: "Search the roadside", effect_description: "The missing cat may be found quickly, but searchers face monster danger." }, { label: "Call from cover", effect_description: "Searchers stay safer, but the missing cat may be too frightened to answer." }, { label: "Send one swift scout", effect_description: "The search is focused, but the scout works alone." }] },
  { id: "crisis_false_omen", type: "crisis", weight: { base: 5, leaf_bare: 7, low_territory: 5 }, icon: "🌘", title: "False Omen", text: "A frightened apprentice claims StarClan sent a sign that the Clan must abandon camp. The medicine cat sees no such message, but fear spreads faster than a vole in bracken.", hasChoice: true, choices: [{ label: "Publicly correct the omen", effect_description: "Panic may stop, but the apprentice feels humiliated." }, { label: "Investigate privately first", effect_description: "Trust is preserved, but rumors continue for another day." }, { label: "Hold a moonlit vigil", effect_description: "The Clan finds unity, but loses valuable rest." }] },
  { id: "crisis_falling_limb", type: "crisis", weight: { base: 5, leaf_bare: 8, low_territory: 5 }, icon: "🌳", title: "Falling Limb", text: "A heavy limb cracks above the Ancient Oak while kits are playing beneath it. Every cat looks up at once. The Clan has seconds to act.", hasChoice: true, choices: [{ label: "Rush the kits away", effect_description: "Kits are safest, but the rescuers may be struck." }, { label: "Yowl for everyone to freeze", effect_description: "Panic may stop, but the branch may fall before cats move." }, { label: "Have warriors push the limb aside", effect_description: "The danger may be controlled, but warriors risk injury." }] },
  { id: "reward_fresh_kill_bonanza", type: "reward", weight: { base: 5, leaf_bare: 3, low_territory: 4 }, icon: "🍖", title: "Fresh-Kill Bonanza", text: "The hunting patrol returns with so much prey that even the elders blink in surprise. A plump squirrel, two mice, and a rabbit fill the pile until kits dance around it chanting warrior names. Tonight, every cat sleeps with a full belly.", hasChoice: false, choices: [] },
  { id: "reward_hidden_mouse_nest", type: "reward", weight: { base: 4, leaf_bare: 5, low_territory: 4 }, icon: "🐭", title: "Hidden Mouse Nest", text: "Beneath a fallen pine branch, a patrol discovers a warm pocket of leaves where mice have been hiding from the cold. The catch is easy, almost as if StarClan nudged the branch aside. The apprentices return proud, whiskers trembling with excitement.", hasChoice: false, choices: [] },
  { id: "reward_herb_patch", type: "reward", weight: { base: 4, leaf_bare: 6, low_territory: 4 }, icon: "🌱", title: "New Herb Patch", text: "A sunny hollow reveals fresh cobweb, borage, and marigold growing together. The medicine cat purrs so loudly that nearby birds scatter. Even the warriors understand that a patch of herbs can be worth more than a pile of prey.", hasChoice: false, choices: [] },
  { id: "reward_kitten_discovery", type: "reward", weight: { base: 3, leaf_bare: 3, low_territory: 3 }, icon: "🐱", title: "A Kit's Clever Discovery", text: "A kit chasing a beetle finds a dry hollow behind the nursery wall. Inside are old feathers, moss, and a smooth stone that glows warmly in sunlight. The queens declare it the finest kit discovery in moons.", hasChoice: false, choices: [] },
  { id: "reward_starcrossed_feather", type: "reward", weight: { base: 3, leaf_bare: 4, low_territory: 3 }, icon: "🪶", title: "Star-Speckled Feather", text: "A silver-speckled feather drifts down in the center of camp though no bird passes overhead. The medicine cat touches it with one paw and smiles. For the rest of the day, cats feel watched over in the gentlest possible way.", hasChoice: false, choices: [] },
  { id: "reward_silver_minnows", type: "reward", weight: { base: 5, leaf_bare: 3, low_territory: 4 }, icon: "🐟", title: "Silver Minnows", text: "Minnows crowd the shallows in such numbers that even clumsy paws catch one. The apprentices squeal with laughter each time water splashes their whiskers. The Clan gains food and a story the kits will beg to hear again.", hasChoice: false, choices: [] },
  { id: "reward_reedbed_vole", type: "reward", weight: { base: 4, leaf_bare: 4, low_territory: 4 }, icon: "🌾", title: "Reedbed Vole", text: "A fat vole blunders from the reeds straight into the path of the patrol. No one moves for a heartbeat because the luck seems too perfect. Then the youngest warrior pounces, and the patrol carries home a prize with proud high tails.", hasChoice: false, choices: [] },
  { id: "reward_moonlit_fish", type: "reward", weight: { base: 3, leaf_bare: 3, low_territory: 3 }, icon: "🌙", title: "Moonlit Fish", text: "Under moonlight, a fish leaps from the ford and lands on the stones at a warrior's paws. The patrol stares, then bursts into delighted purrs. Some gifts from StarClan arrive with no mystery at all, only perfect timing.", hasChoice: false, choices: [] },
  { id: "reward_rare_herbs", type: "reward", weight: { base: 4, leaf_bare: 7, low_territory: 4 }, icon: "🌿", title: "Rare Herbs", text: "The medicine cat finds precious herbs growing in a place everyone thought was barren. Each leaf is gathered with careful thanks, and not a single stem is wasted. The medicine den smells of hope by sunset.", hasChoice: false, choices: [] },
  { id: "reward_rabbit_run", type: "reward", weight: { base: 5, leaf_bare: 3, low_territory: 4 }, icon: "🐇", title: "Rabbit Run", text: "A line of rabbits bolts from the heather after a sudden gust. The patrol moves like one creature, fast and silent. By the time the sun touches the ridge, the fresh-kill pile has enough prey to make every apprentice boast.", hasChoice: false, choices: [] },
  { id: "reward_heather_nest", type: "reward", weight: { base: 3, leaf_bare: 4, low_territory: 3 }, icon: "🛏️", title: "Heather Nesting", text: "Soft heather and dry moss are found tucked beneath a sheltered bank. The queens line the nursery until it smells sweet and warm. Even the fussiest kit curls up without complaint.", hasChoice: false, choices: [] },
  { id: "reward_eagle_feather_sign", type: "reward", weight: { base: 3, leaf_bare: 3, low_territory: 3 }, icon: "🦅", title: "Eagle Feather Sign", text: "A huge feather lies on the ridge, striped with brown and gold. The leader places it above the camp entrance as a sign that the Clan sees far and fears little. Apprentices touch noses to it before training.", hasChoice: false, choices: [] },
  { id: "reward_night_mushroom_glow", type: "reward", weight: { base: 2, leaf_bare: 3, low_territory: 2 }, icon: "🍄", title: "Glow in the Dark", text: "Tiny mushrooms glow blue along the pinebog path, lighting the way just enough for safe paws. The kits decide they are StarClan lanterns. The medicine cat does not correct them.", hasChoice: false, choices: [] },
  { id: "reward_hidden_spring", type: "reward", weight: { base: 3, leaf_bare: 4, low_territory: 3 }, icon: "💦", title: "Hidden Spring", text: "Behind a curtain of roots, a patrol discovers a clear spring that has never frozen. The water tastes clean and cold, with no Twoleg tang. The Clan gains a secret place to drink when the streams turn cruel.", hasChoice: false, choices: [] },
  { id: "reward_peace_token", type: "reward", weight: { base: 3, leaf_bare: 3, low_territory: 5 }, icon: "🤝", title: "Token of Peace", text: "A rival apprentice leaves a bundle of dry moss at the border with no taunt attached. It may be a small apology, or simply kindness from one young cat to another. Either way, the Clan sleeps warmer.", hasChoice: false, choices: [] },
  { id: "reward_kittypet_tip", type: "reward", weight: { base: 2, leaf_bare: 3, low_territory: 2 }, icon: "🏡", title: "Kittypet Tip", text: "A plump kittypet on a fence warns your patrol that Twolegs have left fish scraps near their garden pond. The warriors pretend not to be impressed. By dusk, even the proudest cat admits the tip was useful.", hasChoice: false, choices: [] },
  { id: "reward_ancient_cache", type: "reward", weight: { base: 3, leaf_bare: 5, low_territory: 3 }, icon: "🪨", title: "Ancient Cache", text: "Inside the Ancient Oak, loose bark reveals old dried moss, feathers, and a smooth claw-shaped stone. No cat alive remembers storing them there. The elders say the past has shared its nest with the present.", hasChoice: false, choices: [] }
];

const STORY_ARCS = [
  {
    id: "arc_fire_season",
    title: "The Fire Season",
    theme: "Action/adventure about courage, loyalty, and learning when bravery should leap and when it should wait.",
    ranks: [
      { rank_name: "Spark Kit", xp_threshold: 0, cinematic_title: "The First Warm Ash", cinematic_text: "The first sign comes before {name} is old enough to understand why the elders fall silent. A warm fleck of ash drifts into camp on a windless morning and lands between the tiny paws of the youngest kit in {clan}. The nursery smells of milk, moss, and dandelion fluff, but beneath it is another scent: smoke, faint and old, like a story that has been sleeping under the roots. The queens hurry the kits back, yet {name} keeps staring at the ash because it does not crumble. It glows softly, not hot enough to burn, but bright enough to make every whisker shine. An elder murmurs Firestar's name, and the camp seems to hold its breath. No one says that a kit could matter to a prophecy. No one says that StarClan might choose the smallest pawstep to begin the largest journey. But when the ash finally fades, {name} feels a brave warmth in their chest, as if a hidden star has opened one eye.", starClan_message: "Small paws can stir old embers. Watch the smoke, but do not fear the flame." },
      { rank_name: "Ember Apprentice", xp_threshold: 150, cinematic_title: "Training Beneath Red Leaves", cinematic_text: "{name} becomes an apprentice while the forest is bright with sun and restless birds. The Clan cheers, and {clan} seems larger than it did from the nursery, full of duties that smell of earth, prey, and old promises. Training is not as simple as pouncing on moss. {name} learns that a warrior's leap begins in the shoulders, that scent can change when rain touches it, and that the warrior code is not just words repeated under the sky. It is choosing to feed an elder before taking a bite. It is keeping claws sheathed when pride begs to strike. It is standing still when fear wants to run. One evening, after a long hunt, {name} sees orange light flicker behind the trees. For a heartbeat the whole forest looks aflame, but it is only sunset. Still, the mentor's gaze sharpens. Fire Season has begun, the elders say. Somewhere beyond camp, dry grass waits for one spark, and {name} is learning how sparks become either warmth or ruin.", starClan_message: "An ember may light the den or devour the trees. Learn the shape of your own heat." },
      { rank_name: "Flamepaw Guardian", xp_threshold: 400, cinematic_title: "The Burning Border", cinematic_text: "By the time {name} earns trust on border patrols, every cat in {clan} knows the forest is changing. The streams run thin, moss dries crisp beneath the pads, and prey stays hidden during the hottest part of the day. At the Fallen Log Border, rival scent thickens where it should not be. A proud warrior from another Clan sneers that {clan} guards dust and dead leaves, but {name} notices something worse than insult: smoke moving low between the brambles. The patrol could chase the trespassers and win applause. Instead, {name} calls attention to the wind, the dry fern, the tiny orange tongue licking at a fallen twig. The choice feels like swallowing a thorn, because turning from rivals can look like weakness. Yet when warriors beat dirt over the spark and drag wet moss from a shaded hollow, the border is saved. That night the leader does not praise {name} for winning a fight. The praise is greater than that. {name} protected tomorrow.", starClan_message: "The sharpest claw is not always the one that strikes. Sometimes it points others toward danger." },
      { rank_name: "Ashwhisker Scout", xp_threshold: 800, cinematic_title: "Through the Smoke Path", cinematic_text: "Smoke changes the world into shadows. {name} discovers this when fire finally runs through the outer woods, quick as a fox and twice as hungry. Birds scream from the canopy. Rabbits bolt straight through patrol lines. The sky turns the color of old blood, and {clan} must move before the fire curls around camp. {name} is sent with two warriors to find a path to water, but the familiar trails vanish behind gray walls. It would be easy to panic. Instead, {name} remembers apprentice lessons: feel the slope underpaw, listen for running water, keep the wind at your tail, count every cat after every turn. When a kit begins coughing, {name} carries them by the scruff without waiting to be told. When an elder stumbles, {name} slows the whole line, because no Clan is saved by leaving its memories behind. At last the patrol bursts onto wet stones beside the river. Behind them, the forest burns. Ahead, the Clan lives.", starClan_message: "Ash hides the trail from the eyes, not from the heart. Count every paw you mean to save." },
      { rank_name: "Firebreak Warrior", xp_threshold: 1300, cinematic_title: "The Wall of Living Paws", cinematic_text: "The greatest test comes when the fire turns toward camp itself. No prophecy feels grand then. There is only heat, noise, and the terrible sight of sparks landing on the nursery roof. {name} stands beside the warriors of {clan}, not as the kit who found ash, not as the apprentice who watched sunsets, but as a cat others now look to for direction. The deputy orders a firebreak cut through the dry grass. It sounds impossible. The flames are close, and every warrior is afraid. {name} does not pretend otherwise. Instead, {name} speaks the truth: fear can run faster than fire if every cat runs alone. Together, they claw dirt, drag stones, soak moss, and stamp sparks until paws ache and whiskers singe. Even a rival patrol arrives, stunned into helping by the size of the blaze. When the fire reaches the bare strip, it falters. For one breath, every living cat and every star above seems to push against it. Then the flames bend away.", starClan_message: "A Clan is a wall made of living hearts. Stand together, and even fire must choose another path." },
      { rank_name: "Brightflame Legend", xp_threshold: 2000, cinematic_title: "Where the Forest Grows Again", cinematic_text: "After the Fire Season, the forest is not the same. Blackened trunks stand where green shade once cooled the patrols, and the air smells of rain striking ash. Yet tiny shoots rise from the dark soil, brighter than any victory cry. {name} walks through the recovering woods with the leader of {clan}, listening to birds test the silence. The Clan has lost nests, paths, and easy hunting grounds, but it has not lost itself. Kits are alive. Elders still tell stories. Apprentices still argue about who pounced better. At the Moonpool, the medicine cat dreams of Firestar standing beside unfamiliar starry warriors, his flame-colored pelt shining without burning. He does not speak long. He only looks toward {name}, then toward the new green shoots, as if the meaning should be obvious. Courage is not the fire. Courage is what grows after the fire has passed. When {name} returns to camp, every cat touches noses in greeting, and the ash underpaw feels less like an ending than a beginning.", starClan_message: "The forest remembers flame, but it also remembers rain. Guard what grows next." }
    ],
    choice_points: [
      { setup_text: "A small fire starts near the border while a rival patrol watches from safety.", options: [{ label: "Ask rivals for help immediately", consequence_text: "The fire is contained faster, and a fragile respect forms between patrols, but some proud warriors resent needing aid." }, { label: "Handle it alone", consequence_text: "Clan pride rises if successful, but the blaze may spread and cost precious hunting ground." }, { label: "Accuse the rivals first", consequence_text: "The Clan may expose sabotage if true, but delay makes the fire more dangerous." }] },
      { setup_text: "The camp must be evacuated, but there is not enough time to carry every supply bundle.", options: [{ label: "Carry herbs", consequence_text: "Sick and injured cats survive more easily, but hunger becomes a major problem." }, { label: "Carry fresh-kill", consequence_text: "The Clan avoids immediate hunger, but wounds and coughs become harder to treat." }, { label: "Carry kits and elders only", consequence_text: "The Clan preserves its living heart, but rebuilding becomes harder with few supplies." }] },
      { setup_text: "A rival Clan helped fight the fire and now asks to share a surviving hunting patch.", options: [{ label: "Share the patch for one moon", consequence_text: "Diplomacy improves and future alliances become possible, but prey is stretched thin." }, { label: "Refuse completely", consequence_text: "Territory remains secure, but the rival Clan may become bitter and desperate." }, { label: "Offer prey instead of land", consequence_text: "The Clan shows generosity without surrendering territory, but the fresh-kill pile suffers." }] }
    ],
    breadcrumbs: ["A warm ash fleck appears in camp without any fire nearby.", "Dry fern crackles underpaw even after sunset.", "A rival patrol smells faintly of smoke.", "An elder dreams of Firestar standing beside a wall of flame.", "The river stones grow crowded with thirsty prey.", "A kit draws a flame shape in the dust and forgets doing it.", "The medicine cat finds singed moss near the border.", "Birds abandon one side of the forest before cats smell danger.", "A warrior's whiskers curl from heat no one else felt.", "StarClan sends a dream of rain falling upward.", "The fresh-kill pile dries faster than it should.", "A burned branch points toward the Moonpool.", "Rivals stop taunting when smoke darkens the sky.", "New green shoots appear in blackened soil overnight.", "A silver flame shines briefly in the leader's eyes."],
    lore_fragments: ["Firestar's courage is remembered not because he never feared, but because he acted for others despite fear.", "The warrior code expects cats to protect kits, elders, and the future of the Clan before pride.", "Some fires cleanse deadwood, but no cat should invite flame lightly.", "StarClan often speaks through ordinary things: ash, rain, feathers, and repeated dreams.", "A Clan that survives disaster may become kinder or harder, depending on what its warriors choose.", "Rival Clans may fight over prey, yet all Clans share the same sky of ancestors.", "The Moonpool reflects truth differently for every cat who touches its water.", "New growth after fire is sacred because it proves the forest has not surrendered."]
  },
  {
    id: "arc_long_dark",
    title: "The Long Dark",
    theme: "Dark mystery about hidden fear, lost faith, and finding truth when StarClan seems silent.",
    ranks: [
      { rank_name: "Dusk Listener", xp_threshold: 0, cinematic_title: "When the Stars Go Quiet", cinematic_text: "The first night of the Long Dark does not arrive with claws. It arrives with silence. {name} wakes in the warriors' den and realizes the usual sounds are wrong: no owl calling, no mouse rustling under the wall, no elders shifting in their nests. Above camp, the stars look dim, as if mist has passed between the living world and StarClan. The medicine cat returns from the Moonpool with wet paws and frightened eyes, saying only that the water reflected no sky. For {clan}, this is worse than any fox. A fox can be scented, tracked, and fought. Silence cannot. The youngest apprentices whisper that StarClan has abandoned them. Older warriors snap at them to stop, but their own tails twitch. {name} listens rather than arguing. In the stillness, a tiny sound repeats beneath the bramble wall: scratch, pause, scratch. Something is trying to enter camp, or something already inside is trying to be found.", starClan_message: "When stars hide their faces, listen to the earth. Truth has smaller paws than fear." },
      { rank_name: "Nightpaw Tracker", xp_threshold: 180, cinematic_title: "Clues Beneath Frost", cinematic_text: "{name} learns that mystery is a hunt where the prey wants to be misunderstood. Frost covers the clearing each morning, yet one set of pawprints never frosts over. They cross from the medicine den to the camp entrance, then vanish at the thorn tunnel as if the cat who made them stepped into the air. Some warriors blame rivals. Some blame ghosts. A few, quietly, blame the medicine cat for failing to hear StarClan. {clan} begins to feel divided by glances more than words. {name} refuses to chase the loudest fear. Instead, {name} studies details: the depth of each print, the broken thorn, the strange scent of wet stone. At moonhigh, a hidden tunnel is found beneath old roots, just large enough for a desperate cat. Inside lies a scrap of moss from another Clan's nest and a single black feather. The silence above seems to thicken, but now it has edges. The Long Dark can be tracked.", starClan_message: "Follow what remains when fear has finished speaking. The smallest print may carry the heaviest secret." },
      { rank_name: "Shadow-Sighted Warrior", xp_threshold: 460, cinematic_title: "The Cat Who Was Not There", cinematic_text: "The Clan begins seeing a cat at the edge of camp: dark fur, pale eyes, a tail-tip like drifting smoke. Each time warriors give chase, the stranger disappears, leaving no scent. The apprentices call the figure a ghost, and even the elders stop correcting them. {name} watches from the bramble wall one moonless night while {clan} sleeps uneasily behind. The figure appears beyond the clearing, silent and still. Instead of leaping, {name} waits. The shape flickers when clouds move. It is not a ghost, but a trick of shadow falling across a pale stone, made frightening by fear and rumor. Yet when {name} steps closer, there is a real object tucked behind the stone: a strip of bark scratched with claw marks. The marks count days. Someone has been measuring the Clan's fear, learning when guards grow tired and when patrols change. The enemy may not be dead at all. They may be patient.", starClan_message: "Not every shadow is a spirit. Some are cast by living cats who prefer darkness." },
      { rank_name: "Moonless Seeker", xp_threshold: 900, cinematic_title: "The Silent Moonpool", cinematic_text: "When {name} travels to the Moonpool, the journey feels longer than any border patrol. The path is cold, the stones slick, and the sky above holds stars that seem too distant to care. The medicine cat walks beside {name} without speaking. At the pool, the water is black. No reflection shines there, not even the moon. For a moment, doubt opens its jaws. What is a Clan without StarClan? What is {clan} without the ancestors who guided leaders, comforted queens, and warned medicine cats? {name} lowers their muzzle to the water anyway. The cold strikes like claws, and then a memory rises: not a prophecy, not a voice, but the sound of every living Clanmate breathing in camp. StarClan is not a shortcut around fear. Faith is not proof delivered on command. When {name} lifts their head, a single star appears in the pool, though clouds still cover the sky. The silence is not empty. It is waiting.", starClan_message: "Faith is not the absence of darkness. It is the pawstep taken before dawn agrees to come." },
      { rank_name: "Truthclaw Defender", xp_threshold: 1450, cinematic_title: "The Hidden Enemy", cinematic_text: "The enemy is finally revealed not by battle, but by kindness. A frightened rival apprentice is found near the border, shaking with cold and carrying stolen herbs. Some warriors demand punishment. {name} notices the apprentice is too terrified to be a thief for pride. Slowly, with food and patience, the truth spills out. A secret group from several Clans has been spreading false omens, stealing signs, and darkening the Moonpool with crushed herbs that cloud the water. They believe the Clans grow weak when they trust StarClan too much. They want fear to replace faith so cats will follow any strong voice promising certainty. The news hits {clan} like ice water. Anger rises, but {name} keeps the Clan from turning that anger on every rival. A hidden enemy wanted suspicion to do their work. By refusing to hate blindly, {name} breaks the first trap. The Long Dark is not over, but its shape can now be seen.", starClan_message: "A lie with many claws still bleeds when truth finds it. Do not let anger wear truth's pelt." },
      { rank_name: "Dawnheart Legend", xp_threshold: 2200, cinematic_title: "The Stars Return", cinematic_text: "The final night of the Long Dark gathers every fear into one place. Clouds smother the moon. Rival cats wait beyond the clearing. Inside camp, {clan} stands tense as the false omen-makers attempt their last trick: a staged sign meant to make the leader surrender authority. {name} steps forward before the Clan can fracture. The speech is not grand at first. It is honest. {name} speaks of the ash from the Fire Season, the hidden tunnel, the silent Moonpool, the frightened apprentice, and the difference between faith and obedience. StarClan never asked cats to stop thinking. The warrior code never asked them to stop feeling compassion. One by one, warriors raise their heads. The medicine cat scatters clean water across the false sign, washing away the stain that made it gleam. Above, clouds split. Stars appear in a river of silver, not as an answer to every question, but as witnesses. {name} feels {clan} breathe together again. Dawn is still hours away, yet the dark has lost.", starClan_message: "Stars return to those who remember how to look up. Carry dawn inside you when the sky forgets." }
    ],
    choice_points: [
      { setup_text: "A false omen frightens the apprentices and makes them doubt the medicine cat.", options: [{ label: "Explain the evidence calmly", consequence_text: "Trust grows through reason, but fear fades slowly." }, { label: "Forbid discussion of the omen", consequence_text: "Rumors quiet for now, but hidden doubts become stronger." }, { label: "Let apprentices investigate safely", consequence_text: "They gain courage and critical thinking, but may uncover unsettling clues." }] },
      { setup_text: "A rival apprentice admits stealing herbs because someone threatened their Clan.", options: [{ label: "Protect the apprentice", consequence_text: "The truth may emerge and future alliances improve, but some warriors feel betrayed." }, { label: "Trade the apprentice back", consequence_text: "Diplomacy stays formal, but the secret enemy remains hidden longer." }, { label: "Use the apprentice as bait", consequence_text: "The enemy may be exposed quickly, but the choice violates trust and alarms StarClan." }] },
      { setup_text: "The medicine cat wants to reveal that the Moonpool was deliberately clouded.", options: [{ label: "Tell every cat at once", consequence_text: "The Clan unites around truth, but panic may flare before calm returns." }, { label: "Tell only senior warriors first", consequence_text: "The response is controlled, but younger cats may feel excluded." }, { label: "Wait for stronger proof", consequence_text: "False accusations are avoided, but enemies gain time." }] }
    ],
    breadcrumbs: ["The Moonpool reflects no stars for three nights.", "Pawprints appear without frost inside camp.", "A black feather is found in the medicine den.", "An apprentice dreams of a cat with no scent.", "Clouded water smells faintly of crushed herbs.", "A rival elder denies a border patrol that everyone saw.", "Moss goes missing from nests but not from the storage pile.", "The same claw mark appears on three different trees.", "A kit hears scratching beneath the camp wall.", "A false StarClan sign shines only when wet.", "The medicine cat's dreams return as fragments, not words.", "A frightened rival apprentice carries stolen catmint.", "Someone has counted guard changes on bark.", "A shadow turns out to be a stone, but the stone hides a message.", "The first returning star appears in water before sky."],
    lore_fragments: ["Medicine cats serve StarClan, but they must also use courage, memory, and judgment.", "False omens are dangerous because they steal trust from both the living and the dead.", "Darkness can make loyal cats suspect one another before any enemy lifts a claw.", "The Moonpool is sacred, but even sacred places can be threatened by living paws.", "A Clan's faith grows stronger when questions are allowed to stand beside belief.", "The warrior code rejects cruelty even when fear makes cruelty tempting.", "Some enemies prefer rumors to battles because rumors wound without leaving scent.", "Dawn is a promise made slowly, one pale line at a time."]
  },
  {
    id: "arc_gathering_storm",
    title: "The Gathering Storm",
    theme: "Political intrigue about leadership, alliances, rival pressure, and the cost of peace.",
    ranks: [
      { rank_name: "Gathering Witness", xp_threshold: 0, cinematic_title: "The Full Moon Fractures", cinematic_text: "The first Gathering after the Long Dark should feel like relief. Instead, the island hums with unease. Leaders stand beneath the full moon with polished voices and guarded eyes, while deputies measure one another like warriors circling before a fight. {name} sits with the cats of {clan}, listening for what is not being said. Prey is scarce in one territory. A border marker has been moved in another. Someone accuses a medicine cat of hiding a prophecy. The moon remains clear, so StarClan has not forbidden the Gathering, but clouds gather at the edges of the sky like listening shadows. When a rival leader praises {name} too warmly, several cats turn to stare. Compliments can be claws wrapped in moss. On the walk home, the leader asks what {name} noticed. Not the loud accusations. Not the dramatic tail-lashing. {name} noticed which cats exchanged glances when peace was mentioned. The storm coming now will not begin with thunder. It will begin with promises.", starClan_message: "A smooth tongue may hide sharper teeth than battle. Listen for the promise that costs too little." },
      { rank_name: "Treaty Paw", xp_threshold: 220, cinematic_title: "Moss Between Claws", cinematic_text: "{name} is asked to attend a border talk, not as leader, not as deputy, but as a cat both sides remember from fire and darkness. The meeting place is a flat stone between scentlines, carefully chosen so no Clan can claim insult. The rival envoy arrives with two guards and a smile that does not reach the eyes. They offer shared patrols against foxes, shared herbs in leaf-bare, and a temporary prey exchange. Every offer sounds reasonable. That is what makes it dangerous. {clan} needs allies, but not chains disguised as vines. {name} notices the envoy never says how long temporary means. They never name which border paths will be shared. They never promise to respect the nursery during shortages. When {name} asks for clear terms, the smile fades. Good. A true friend can bear honest questions. A cat laying a trap hates when the moss is pulled aside and the thorns show underneath.", starClan_message: "Peace with no shape becomes a den with no walls. Name the boundary before you sleep inside it." },
      { rank_name: "Scentline Diplomat", xp_threshold: 560, cinematic_title: "The Price of One Rabbit", cinematic_text: "A single rabbit nearly starts a war. It falls on disputed ground after a chase that began in {clan} territory and ended near a rival marker. Both patrols claim it. Hungry cats do not argue gently. Claws slide out, apprentices puff up, and old insults rise faster than sense. {name} steps between the patrols with the rabbit at their paws, feeling how easily one wrong word could become a moon of raids. The solution is not perfect, because politics rarely gives perfect prey. {name} proposes the rabbit go to the Clan with the hungriest kits, witnessed by both patrols, while the scentline is re-marked together at dawn. Some warriors grumble. One rival sneers. But a queen on the other side lowers her head in thanks, and the sneer loses power. That night, {name} learns that fairness does not always feel like victory. Sometimes it feels like letting pride go hungry so kits do not have to.", starClan_message: "The prey you surrender may feed the peace that saves ten hunts. Count beyond one rabbit." },
      { rank_name: "Whisper Councilor", xp_threshold: 1050, cinematic_title: "Secrets Under Leader's Rock", cinematic_text: "The conspiracy reaches camp through whispers. A respected warrior claims the leader is too soft. Another says {clan} should seize land while rivals recover from sickness. A third repeats a rumor that {name} is loyal to outsiders because they once spared a rival apprentice. The words spread under Leader's Rock like roots seeking cracks. Fighting such rumors with louder rumors would poison the same soil. {name} chooses the harder path: open council. Every warrior may speak, but every claim must be named, witnessed, and answered. It is messy. Feelings bruise. Old resentments crawl into daylight. Yet something powerful happens when cats must stand beside their own words. The boldest liar grows smaller. The worried cats discover they are not alone. The leader admits mistakes without surrendering authority. By moonrise, {clan} is tired, but clearer. Secrets thrive in sealed dens. Open air does not kill every thorn, but it shows where they grow.", starClan_message: "A Clan that cannot hear hard truths will hear easy lies. Let daylight enter before rot learns the tunnels." },
      { rank_name: "Storm-Speaker", xp_threshold: 1650, cinematic_title: "The Broken Truce", cinematic_text: "The truce breaks during rain. A rival patrol crosses the border claiming pursuit of a fox, but their pawprints spread too wide and too neatly. This was no accident. Warriors of {clan} bristle for battle, and even {name} feels the pull of righteous fury. The rival leader has counted on that. If {clan} attacks first, every promise made at the Gathering can be twisted into accusation. If {clan} does nothing, territory becomes an open door. {name} sends three patrols: one to block the rivals without striking, one to track the supposed fox, and one to escort a medicine cat to the shared meeting stone as witness. The maneuver is risky because it requires discipline from angry cats. It works because they trust {name}. By sunset, the lie is exposed: no fox, only staged tracks. At the next Gathering, {name} speaks with calm so sharp it cuts deeper than yowling. Storms can be answered without becoming storm yourself.", starClan_message: "Thunder shakes the trees, but rain reveals the tracks. Let proof fall where anger wants to leap." },
      { rank_name: "Skywatch Envoy", xp_threshold: 2500, cinematic_title: "The Council of Four Winds", cinematic_text: "The final storm gathers under a full moon bright enough to silver every whisker. All Clans come to the council, not because they trust one another fully, but because they have learned what distrust alone can cost. {name} stands beside the leader of {clan}, feeling the weight of every choice that led here: the shared firebreak, the false omen exposed, the rabbit surrendered, the rumors dragged into daylight. Around the clearing, rivals wait to see whether the future will be claws or code. A proud leader demands punishment. A hungry deputy demands land. A medicine cat asks everyone to remember that StarClan watches all Clans, not just the loudest one. Then {name} speaks. The words do not erase old wounds. They do not make every border easy. But they name a new pact: medicine cats safe in all territories, kits never used as threats, disputed prey judged by need and witness, and false omens treated as crimes against every Clan. When the moon clears the last cloud, no cat cheers at first. The peace is too serious for cheering. Then one apprentice begins to purr, and slowly the sound spreads like rain after drought.", starClan_message: "The sky is wide enough for many Clans, but not for endless pride. Guard the peace as fiercely as prey." }
    ],
    choice_points: [
      { setup_text: "A rival Clan offers an alliance with vague terms and flattering promises.", options: [{ label: "Accept immediately", consequence_text: "Relations improve quickly, but the Clan may be trapped by unclear obligations." }, { label: "Demand written terms witnessed at the Gathering", consequence_text: "Trust builds more slowly, but the agreement becomes harder to twist." }, { label: "Reject all alliances", consequence_text: "Independence is protected, but the Clan stands alone during the next crisis." }] },
      { setup_text: "A rumor spreads that the leader is hiding prey from hungry warriors.", options: [{ label: "Open the stores for public counting", consequence_text: "Trust increases through transparency, but enemies learn exactly how weak supplies are." }, { label: "Punish the rumor-spreader", consequence_text: "Order returns quickly, but secret resentment grows." }, { label: "Question the rumor-spreader privately", consequence_text: "The source may be exposed, but public doubt remains longer." }] },
      { setup_text: "At the final council, one Clan demands land as payment for peace.", options: [{ label: "Offer temporary hunting rights instead", consequence_text: "Immediate hunger is addressed without permanent surrender, but patrol schedules become complicated." }, { label: "Refuse and risk conflict", consequence_text: "Territory remains intact, but the council may collapse." }, { label: "Create a shared neutral hunting ground", consequence_text: "Peace becomes possible, but every Clan must sacrifice some control." }] }
    ],
    breadcrumbs: ["A rival leader praises the Clan too loudly at the Gathering.", "A border marker is moved exactly one tail-length.", "Three Clans report fox trouble on the same night.", "A deputy refuses to meet another deputy's eyes.", "The same phrase appears in rumors across different camps.", "A medicine cat is asked to carry a political message and refuses.", "A rabbit dies on disputed ground.", "Kits repeat insults they could only have learned from warriors.", "A leader offers prey but not safe passage.", "A treaty uses the word temporary without saying how many moons.", "A false fox trail is made with dragged fur.", "The full moon dims but does not cloud over.", "An apprentice purrs during a tense council and breaks the silence.", "A rival queen thanks the patrol without words.", "The final pact is scratched into bark beneath the Ancient Oak."],
    lore_fragments: ["Gatherings are protected by the full moon, but StarClan does not make cats honest.", "The warrior code is strongest when leaders apply it even to rivals.", "Diplomacy can be as dangerous as battle because claws are easier to see than bargains.", "A Clan that hoards safety may find itself alone when danger grows.", "Medicine cats carry sacred duties that should not be twisted into politics.", "Public truth can hurt, but secret suspicion often hurts longer.", "A fair compromise may disappoint every side and still save every side.", "Peace is not the absence of borders; it is the promise to respect them."]
  }
];

const CAT_NAMES = {
  prefixes: ["Amber","Ash","Beech","Birch","Blue","Bramble","Bright","Brook","Cinder","Cloud","Dawn","Dove","Drift","Echo","Ember","Fawn","Feather","Fern","Fire","Frost","Golden","Hawk","Heather","Holly","Ivy","Jay","Leaf","Lily","Mist","Moss","Night","Oak","Pebble","Rain","Raven","Reed","Ripple","Rowan","Silver","Storm"],
  suffixes: ["heart","claw","pelt","fur","tail","stripe","whisker","leaf","flower","storm","flight","stream","pool","feather","shine","step","song","nose","fang","breeze","shade","fall","spring","brook"]
};

const PROPHECIES = {
  ThunderClan: ["When ash warms beneath green leaves, the smallest spark will choose whether the forest burns or blooms.", "A claw held back beneath thunder will save more lives than a claw raised in pride.", "Look for the flame that casts no shadow, for it will lead ThunderClan through smoke."],
  RiverClan: ["When the river forgets the moon, follow the fish that swims against silver light.", "A reed that bends before the flood will stand when stone is swallowed.", "The deepest current carries a secret, and only patient paws will feel it pass."],
  WindClan: ["When the moor wind turns in circles, the swiftest cat must learn to stand still.", "A rabbit's path will cross a storm's path, and hunger must not outrun wisdom.", "Beneath open sky, the hidden truth will have nowhere left to crouch."],
  ShadowClan: ["When pine roots drink black water, a shadow will choose whether to shelter or strike.", "The eye that shines in darkness is not always an enemy, and not always a friend.", "A secret buried in bog mud will rise when three Clans refuse to look away."]
};

const SEASON_FLAVOR = {
  Greenleaf: { arrival_text: "Greenleaf arrives with warm stones, buzzing bees, and prey-scent drifting through every fern tunnel.", midseason_text: "The sun rides high over the trees, and patrols return dusty, thirsty, and proud of heavy fresh-kill." },
  "Leaf-fall": { arrival_text: "Leaf-fall scatters gold and red across the territory, hiding pawprints beneath crisp leaves.", midseason_text: "Cold winds tug at the dens, and every warrior knows full bellies now will matter when snow comes." },
  "Leaf-bare": { arrival_text: "Leaf-bare grips the forest with frozen claws, thinning prey and turning every cough into a warning.", midseason_text: "Snow muffles the camp, herbs run low, and the Clan survives by sharing warmth, prey, and courage." },
  Newleaf: { arrival_text: "Newleaf pushes green shoots through old frost, and the first birdsong makes the nursery kits squeak with joy.", midseason_text: "Rain softens the earth, herbs rise fresh, and apprentices return from training with muddy paws and bright eyes." }
};

const UPGRADE_TEXT = {
  fresh_kill_pile: ["The fresh-kill pile is reinforced with cool stones, and the Clan cheers the promise of safer, longer-lasting prey.", "New shade over the fresh-kill pile keeps prey fresh, making every hunter's catch feel twice as valuable.", "The completed fresh-kill store smells of clean leaves and abundance, and even the elders praise the clever work."],
  medicine_den: ["The medicine den is lined with dry moss and sorted herbs, giving every sick cat a better chance to heal.", "Fresh shelves of bark and stone let the medicine cat store remedies with proud, careful paws.", "The upgraded medicine den feels calm and sacred, as if StarClan itself has breathed warmth into the walls."],
  training_grounds: ["The training grounds are cleared and marked, ready for apprentices to practice leaps, rolls, and brave recoveries.", "New moss dummies and scratch logs turn training into a challenge every young cat wants to conquer.", "The finished training grounds ring with excited yowls as mentors prepare the next generation of warriors."],
  watchtower: ["The watchtower rises above camp, giving sharp-eyed guards a clear view of border paths and storm clouds.", "Reinforced branches make the watchtower steady underpaw, and patrol leaders purr at the improved sightlines.", "From the completed watchtower, the Clan can see danger sooner and greet dawn like true guardians."],
  nursery: ["The nursery is tucked with warm moss and soft feathers, making the kits tumble with delighted squeaks.", "A stronger bramble wall protects the nursery, and every queen rests easier behind its woven thorns.", "The completed nursery feels like the heartbeat of camp, safe, warm, and full of tiny future warriors."],
  leaders_rock: ["Leader's Rock is cleared of loose stones, giving the leader a proud place to address the Clan.", "New claw marks around Leader's Rock honor past leaders while inviting future courage.", "The finished Leader's Rock gleams under moonlight, ready for ceremonies, hard truths, and Clan triumphs."]
};

const RIVAL_TAUNTS = {
  BlazeClan: ["Careful, little sparks. BlazeClan knows how to turn a border mistake into wildfire.", "Your patrols smell nervous from here. Try not to trip over your own tails.", "We leave ash where we walk and legends where we fight."],
  MistClan: ["You cannot claw what you cannot see, and MistClan is already behind you.", "Your scent markers wash away so easily. How do you remember what is yours?", "The fog is kind to clever cats and cruel to loud ones."],
  IronClan: ["Soft paws, soft rules, soft borders. IronClan will test them all.", "We do not bend because the wind complains.", "Bring your best warriors. We sharpen our claws on bigger threats."],
  StormClan: ["Hear that thunder? It is only StormClan stretching before the real strike.", "Your camp looks peaceful. Peace is what cats call the moment before we arrive.", "When clouds gather, wise cats seek shelter from us."],
  AncientClan: ["We walked these roots before your elders had names.", "Your Clan remembers stories; AncientClan remembers truth.", "Bow to the old paths, young warriors, or be lost among them."]
};

export { ZONES, EVENTS, STORY_ARCS, CAT_NAMES, PROPHECIES, SEASON_FLAVOR, UPGRADE_TEXT, RIVAL_TAUNTS };
